### ISSUE TITLE
Compatibility with IDEA 16

### ISSUE THREAD

**Issue by AlexejK** [cholick/idea-spock-enhancements#28]
Latest EAP 16 causes issues with the plugin during startup. 

IntelliJ IDEA (Minerva) IU-144.3357.4
Build #IU-144.3357, built on January 26, 2016

Error below:

`Plugin 'Spock Framework Enhancements' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:520)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:154)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:511)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:491)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:484)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1263)
    at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:31)
    at com.intellij.openapi.application.Preloader$2$1.run(Preloader.java:78)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.Preloader$2.run(Preloader.java:74)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:172)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:484)
    ... 17 more
Caused by: java.lang.NullPointerException
    at com.cholick.idea.spock.actions.NewSpockSpecAction.<init>(NewSpockSpecAction.java:43)
    ... 22 more
`

**Comment by sgitt** [comment]
Event log entry:
`Throwable: Null child action in group New () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=Spock.NewSpec`

**Comment by cholick** [comment]
Fixed
